### PR TITLE
Change preprocess files naming to avoid cache

### PR DESCRIPTION
**Pull request by peilingjiang**
Avoid models trained all become the same as the first one when running a continues training script for multiple models. Also adjust hyperparameter names in README to make it easier to understand.

### CODE REVIEW

**Comment by peilingjiang** [comment]
#18

**Comment by shiffman** [comment]
Fantastic, thank you for this @peilingjiang! Do you think it would make more sense to write these files out to a different directory and not the input one?

**Comment by peilingjiang** [comment]
@shiffman Thank you for pointing that out! I've changed the directory storing the processed files and now they'll be stored in a new folder in the root directory.

**Comment by shiffman** [comment]
Wonderful, thank you!

**Pull request merged**
