### PR TITLE
Add print_every and total_time

### PR DESCRIPTION
**Pull request by peilingjiang**
Add arguments controlling printing frequency and total time display.

### CODE REVIEW

**Comment by shiffman** [comment]
Thank you @peilingjiang! I've made some changes to the way this works in anticipation of class tomorrow in #15. Once I merge that there may end up being conflicts with this pull request. We can work on resolving them! Just a heads up for now!

**Comment by shiffman** [comment]
Hi @peilingjiang if you want to check the conflicts I can merge this!

**Comment by peilingjiang** [comment]
> Hi @peilingjiang if you want to check the conflicts I can merge this!

Resolved the conflicts!

**Comment by shiffman** [comment]
Thanks!

**Pull request merged**
